name: home_control
description: "Home control panel"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0-196.0.dev

dependencies:
  shelf: ^1.4.2
  address: ^0.1.0+2
  crypto: ^3.0.7
  vector_math: ^2.2.0
  http: ^1.6.0
  path_provider: ^2.1.5